client
dev tun
proto udp

# Endereço do servidor VPN (LAB05 passo 7)
remote 6.6.6.1 1194

# Certificados e chaves do cliente (LAB05 passo 6)
ca ca.crt
cert ana.crt
key ana.key

# Cifra obrigatória pelo enunciado
cipher AES-128-GCM

# tls-auth: direction 1 = cliente (LAB05 passo 4)
tls-auth ta.key 1

resolv-retry infinite
nobind
persist-key
persist-tun

verb 3