port 1194
proto udp
dev tun

#certificados e chaves
ca ca.crt
cert server.crt
key server.key
dh dh.pem

#subrede VPN — clientes recebem IPs 10.8.0.x (LAB05 passo 10)
server 10.8.0.0 255.255.255.0

#push rota APENAS para a rede corporate
push "route 16.2.4.0 255.255.255.0"

#cifra obrigatória pelo enunciado: AES-128-GCM
cipher AES-128-GCM

#tls-auth: direction 0 = servidor
tls-auth ta.key 0

keepalive 10 120
persist-key
persist-tun

verb 3
status openvpn-status.log