client
dev tun
proto udp

# Endereço do servidor VPN 
remote 6.6.6.1 1194 

# Certificados e chaves do cliente (A ÚNICA DIFERENÇA ESTÁ AQUI)
ca ca.crt
cert bento.crt
key bento.key

# Cifra obrigatória pelo enunciado
cipher AES-128-GCM

# tls-auth: direction 1 = cliente
tls-auth ta.key 1

resolv-retry infinite
nobind
persist-key
persist-tun
verb 3